//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaboradores
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string estado_civil { get; set; }
        public string grado_academico { get; set; }
        public string direccion { get; set; }
    }
}
